### ISSUE TITLE
release error

### ISSUE THREAD

**Issue by Krishsinghal123** [tomwillfixit/honeypot#1]
![tomwillfixit](https://user-images.githubusercontent.com/29298488/36355100-e7a9d56e-1503-11e8-9190-c09cfccfe3a4.png)
$This is the error I'm getting, is it still fine to run the honeypot?

**Comment by Krishsinghal123** [comment]
When I run the command: "docker run -p 22:22 --name honeypot -dt ssh_honeypot:latest"
This is what I get, " Unable to find image 'ssh_honeypot:latest' locally docker: Error response from daemon: pull access denied for ssh_honeypot, repository does not exist or may require 'docker login'.
See 'docker run --help'."
Also tried "docker run -p 22:22 --name honeypot -dt ssh_honeypot", gives the same result.

**Comment by tomwillfixit** [comment]
Looks like an issue with the ubuntu repositories. Are you behind a firewall that might be restricting access to the repos? The docker run command won't work until docker build passes. I'll try to build later today.

**Comment by Krishsinghal123** [comment]
No, I don't use firewalls. I'm using Ubuntu16.04, 64bit.

**Comment by Krishsinghal123** [comment]
Did you try that? I want to run this.

**Comment by tomwillfixit** [comment]
Fixed now. Works with ubuntu:17.10 base image.

**Comment by Krishsinghal123** [comment]
Will that work for 16.04?
